name: Host Service CI
on:
  push:
    branches:
      - 'main'
    paths:
      - '*.js'
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1.Checkout
      uses: actions/checkout@v2   # @v3 is not available as of my last training data in September, 2021. Please verify the latest version.

    - name: 2.Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 2.5 Builld Setting
      uses: docker/setup-buildx-action@v2

    - name: 3. Builld and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tofudocker/hostservice:${{ github.sha }}

  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage  # Make sure the buildImage job completes before this job starts
    steps:
      - name: 1.Checkout
        uses: actions/checkout@v2   # Change from docker/checkout@v3 to actions/checkout@v2
        with:
          repository: 'malangtofu/hostsvc-cd'
          token : ${{ secrets.GITHAB_TOKEN }}   # Make sure the spelling is GITHUB_TOKEN

      - name: 2. Change Docker Tag
        run: |
          sed -i "s|image: tofudocker/node-app:.*|image: tofudocker/node-app:${{ github.sha }}|g" /path/to/your/file   # Add -i to update the file in-place, and specify the file path
          git config --global user.email "malangtofu507@gmail.com"
          git config --global user.name "malangtofu"
          git commit -am "triggered by github action"
          git push origin main